base:
  path: /
  controller: App\Controller\MainController::index
about:
  path: /about
  controller: App\Controller\MainController::about
  methods: ['GET']
products:
  path: /products
  controller: App\Controller\MainController::products
  methods: ['GET']
single:
  path: /single
  controller: App\Controller\MainController::single
  methods: ['GET']

contact:
  path: /contact
  controller: App\Controller\MainController::contact
  methods: ['GET']



